FROM python:3.9-slim as builder
WORKDIR /szr
COPY ./requirements.txt ./requirements.txt
RUN python -m venv /szr/venv  \
    && /pity/venv/bin/python -m pip install --upgrade pip \
    && /pity/venv/bin/python -m pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ \
    && apt update -y \
    && apt upgrade -y \
    && apt install -y tzdata \
    && apt install -y wget \
    && wget https://github.com/vishnubob/wait-for-it/raw/master/wait-for-it.sh


FROM python:3.9-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /pity
COPY . .
COPY --from=builder /szr/venv/ /szr/venv/
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY --from=builder /szr/wait-for-it.sh /szr/ops/wait-for-it.sh
RUN ln -sf /szr/ops/dev.env.ops /szr/conf/dev.env \
    && chmod +x /szr/ops/wait-for-it.sh

EXPOSE 7777

CMD ["/szr/venv/bin/supervisord", "-c", "/szr/ops/supervisor.conf"]