version: "3"
services:

  pity:
    build:
      context: ../
      dockerfile: ops/dockerfile
      args:
        buildno: 1
    container_name: szr_server
    ports:
      - "7777:7777"
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      szr_net:
        aliases:
        - szr_server
    volumes:
      - ./dev.env.ops:/szr/conf/dev.env

networks:
  szr_net: